import config from '@/config/config';
import logger from '@/config/logger';

import { GhlApiError } from './ghl.client';
import type { GhlToken } from './ghl.types';

/**
 * GoHighLevel Media Library uploads.
 *
 * Kept out of `ghlRequest` on purpose: that helper JSON-stringifies every body
 * and pins `Content-Type: application/json`, which multipart uploads cannot
 * use - the boundary must be generated by the runtime. Everything else
 * (auth header, Version header, timeout, User-Agent) is mirrored here so the
 * two paths behave the same.
 */

const USER_AGENT = `${config.appName.replace(/\s+/g, '-')}/1.0`;

/** Uploads are far slower than JSON calls, so they get their own budget. */
const UPLOAD_TIMEOUT_MS = 120_000;

export interface GhlMediaFile {
  /** GoHighLevel's media file id. */
  fileId: string;
  /** Publicly reachable URL of the stored object. */
  url: string;
  name: string;
}

export interface UploadMediaParams {
  token: GhlToken;
  locationId: string;
  /** Final filename in the Media Library - already prefixed with the contact id. */
  fileName: string;
  mimeType: string;
  buffer: Buffer;
}

/**
 * `POST /medias/upload-file` into a sub-account's Media Library.
 *
 * Always uploads with the FIRM's own location token, never the agency token -
 * that is what keeps one firm's client documents inside that firm's
 * sub-account and invisible to every other tenant.
 */
export const uploadMedia = async (params: UploadMediaParams): Promise<GhlMediaFile> => {
  if (!config.ghl.enabled) {
    throw new GhlApiError('GoHighLevel is disabled - set GHL_ENABLED=true', 503);
  }
  if (!params.token.accessToken) {
    throw new GhlApiError('Missing GoHighLevel sub-account token', 401);
  }

  const form = new FormData();
  form.append(
    'file',
    new Blob([new Uint8Array(params.buffer)], { type: params.mimeType }),
    params.fileName
  );
  form.append('name', params.fileName);
  // altId/altType scope the upload to this sub-account's library.
  form.append('altId', params.locationId);
  form.append('altType', 'location');

  const url = `${config.ghl.apiBaseUrl.replace(/\/+$/, '')}/medias/upload-file`;
  const startedAt = Date.now();

  let response: Response;
  try {
    response = await fetch(url, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${params.token.accessToken}`,
        Version: config.ghl.apiVersion,
        Accept: 'application/json',
        'User-Agent': USER_AGENT,
        // Content-Type is deliberately omitted - fetch sets it with the
        // multipart boundary, and setting it by hand breaks the upload.
      },
      body: form,
      signal: AbortSignal.timeout(UPLOAD_TIMEOUT_MS),
    });
  } catch (error) {
    const isTimeout =
      error instanceof Error && (error.name === 'TimeoutError' || error.name === 'AbortError');
    throw new GhlApiError(
      isTimeout ? 'Upload to GoHighLevel timed out' : 'Could not reach GoHighLevel',
      0
    );
  }

  const text = await response.text();
  let parsed: unknown;
  try {
    parsed = text ? JSON.parse(text) : undefined;
  } catch {
    parsed = text;
  }

  if (!response.ok) {
    const message =
      parsed && typeof parsed === 'object' && 'message' in parsed
        ? String((parsed as { message: unknown }).message)
        : `GoHighLevel upload failed with status ${response.status}`;
    throw new GhlApiError(message, response.status);
  }

  // GHL has returned this under a few shapes across versions; accept them all
  // rather than breaking on a field rename.
  const record = (parsed ?? {}) as Record<string, unknown>;
  const nested = (record.file ?? record.data ?? {}) as Record<string, unknown>;
  const fileId = String(record.fileId ?? record._id ?? record.id ?? nested._id ?? nested.id ?? '');
  const fileUrl = String(record.url ?? record.fileUrl ?? nested.url ?? '');

  if (!fileId && !fileUrl) {
    throw new GhlApiError('GoHighLevel accepted the upload but returned no file reference', 502);
  }

  logger.info(
    `GHL media upload ok: ${params.fileName} -> ${fileId || '(no id)'} in ${
      Date.now() - startedAt
    }ms`
  );

  return { fileId, url: fileUrl, name: params.fileName };
};
